### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DamianosS** [steffenmllr/node-red-contrib-speedtest#20]
I couldn't install the node via "Manage Palette". 
I'm running Node-RED v3.0.0

Following error:

`
-----------------------------------------------------------
2022-07-19T18:06:35.637Z Install : node-red-contrib-speedtest 1.1.0

2022-07-19T18:06:35.444Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-speedtest@1.1.0
2022-07-19T18:06:36.630Z [err] npm
2022-07-19T18:06:36.632Z [err]  WARN config production Use `--omit=dev` instead.
2022-07-19T18:06:52.603Z [err] npm WARN
2022-07-19T18:06:52.603Z [err]  deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
2022-07-19T18:06:54.834Z [err] npm 
2022-07-19T18:06:54.834Z [err] ERR! code 1
2022-07-19T18:06:54.834Z [err] npm ERR! path /config/node-red/node_modules/lzma-native
2022-07-19T18:06:54.838Z [err] npm ERR!
2022-07-19T18:06:54.838Z [err]  command failed
2022-07-19T18:06:54.838Z [err] npm ERR! command sh -c node-pre-gyp install --fallback-to-build && rimraf build
2022-07-19T18:06:54.839Z [err] npm 
2022-07-19T18:06:54.839Z [err] ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python3' (1)
2022-07-19T18:06:54.839Z [err] npm 
2022-07-19T18:06:54.839Z [err] ERR! node-pre-gyp info it worked if it ends with ok
2022-07-19T18:06:54.839Z [err] npm ERR!
2022-07-19T18:06:54.839Z [err]  node-pre-gyp info using node-pre-gyp@0.11.0
2022-07-19T18:06:54.839Z [err] npm ERR!
2022-07-19T18:06:54.839Z [err]  node-pre-gyp info using node@16.15.0 | linux | x64
2022-07-19T18:06:54.840Z [err] npm ERR!
2022-07-19T18:06:54.840Z [err]  node-pre-gyp WARN Using request for node-pre-gyp https download 
2022-07-19T18:06:54.840Z [err] npm ERR!
2022-07-19T18:06:54.840Z [err]  node-pre-gyp info check checked for "/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node" (not found)
2022-07-19T18:06:54.840Z [err] npm ERR!
2022-07-19T18:06:54.840Z [err]  node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-linux-x64.tar.gz
2022-07-19T18:06:54.840Z [err] npm ERR! node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-linux-x64.tar.gz
2022-07-19T18:06:54.840Z [err] npm ERR! node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-linux-x64.tar.gz 
2022-07-19T18:06:54.840Z [err] npm ERR! node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.6 and node@16.15.0 (node-v93 ABI, musl) (falling back to source compile with node-gyp) 
2022-07-19T18:06:54.840Z [err] npm
2022-07-19T18:06:54.840Z [err]  ERR! node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v93-linux-x64.tar.gz 
2022-07-19T18:06:54.840Z [err] npm
2022-07-19T18:06:54.841Z [err]  ERR! gyp info it worked if it ends with ok
2022-07-19T18:06:54.841Z [err] npm
2022-07-19T18:06:54.841Z [err]  ERR! gyp info using node-gyp@9.0.0
2022-07-19T18:06:54.841Z [err] npm
2022-07-19T18:06:54.841Z [err]  ERR! gyp info using node@16.15.0 | linux | x64
2022-07-19T18:06:54.841Z [err] npm
2022-07-19T18:06:54.841Z [err]  ERR! gyp info ok 
2022-07-19T18:06:54.841Z [err] npm 
2022-07-19T18:06:54.841Z [err] ERR! gyp info it worked if it ends with ok
2022-07-19T18:06:54.841Z [err] npm 
2022-07-19T18:06:54.841Z [err] ERR! gyp info using node-gyp@9.0.0
2022-07-19T18:06:54.841Z [err] npm ERR!
2022-07-19T18:06:54.841Z [err]  gyp info using node@16.15.0 | linux | x64
2022-07-19T18:06:54.841Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python 
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python Python is not set from environment variable PYTHON
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python checking if "python3" can be used
2022-07-19T18:06:54.842Z [err] npm ERR!
2022-07-19T18:06:54.842Z [err]  gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-07-19T18:06:54.842Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-07-19T18:06:54.842Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python 
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2022-07-19T18:06:54.843Z [err] npm
2022-07-19T18:06:54.843Z [err]  ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-07-19T18:06:54.843Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-07-19T18:06:54.843Z [err] npm
2022-07-19T18:06:54.843Z [err]  ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-07-19T18:06:54.843Z [err] npm
2022-07-19T18:06:54.844Z [err]  ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-07-19T18:06:54.844Z [err] npm 
2022-07-19T18:06:54.844Z [err] ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-07-19T18:06:54.844Z [err] npm
2022-07-19T18:06:54.844Z [err]  ERR! gyp ERR! find Python For more information consult the documentation at:
2022-07-19T18:06:54.844Z [err] npm 
2022-07-19T18:06:54.844Z [err] ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-07-19T18:06:54.844Z [err] npm 
2022-07-19T18:06:54.844Z [err] ERR! gyp ERR! find Python **********************************************************
2022-07-19T18:06:54.844Z [err] npm 
2022-07-19T18:06:54.844Z [err] ERR! gyp ERR! find Python 
2022-07-19T18:06:54.844Z [err] npm ERR!
2022-07-19T18:06:54.844Z [err]  gyp ERR! configure error 
2022-07-19T18:06:54.844Z [err] npm ERR!
2022-07-19T18:06:54.845Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2022-07-19T18:06:54.845Z [err] npm ERR!
2022-07-19T18:06:54.845Z [err]  gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-07-19T18:06:54.845Z [err] npm 
2022-07-19T18:06:54.845Z [err] ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-07-19T18:06:54.845Z [err] npm
2022-07-19T18:06:54.845Z [err]  ERR!
2022-07-19T18:06:54.845Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-07-19T18:06:54.845Z [err] npm ERR!
2022-07-19T18:06:54.845Z [err]  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-07-19T18:06:54.845Z [err] npm
2022-07-19T18:06:54.845Z [err]  ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-07-19T18:06:54.846Z [err] npm 
2022-07-19T18:06:54.846Z [err] ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-07-19T18:06:54.846Z [err] npm 
2022-07-19T18:06:54.846Z [err] ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-07-19T18:06:54.846Z [err] npm 
2022-07-19T18:06:54.846Z [err] ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-07-19T18:06:54.846Z [err] npm 
2022-07-19T18:06:54.846Z [err] ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-07-19T18:06:54.846Z [err] npm ERR!
2022-07-19T18:06:54.846Z [err]  gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-07-19T18:06:54.846Z [err] npm ERR!
2022-07-19T18:06:54.846Z [err]  gyp ERR! System Linux 5.15.45
2022-07-19T18:06:54.846Z [err] npm ERR!
2022-07-19T18:06:54.847Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93" "--python=/usr/bin/python3"
2022-07-19T18:06:54.847Z [err] npm 
2022-07-19T18:06:54.847Z [err] ERR!
2022-07-19T18:06:54.849Z [err]  gyp ERR! cwd /config/node-red/node_modules/lzma-native
2022-07-19T18:06:54.849Z [err] npm ERR! gyp ERR! node -v v16.15.0
2022-07-19T18:06:54.849Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-07-19T18:06:54.849Z [err] npm ERR! gyp ERR! not ok 
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! build error 
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/config/node-red/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python3' (1)
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! System Linux 5.15.45
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/config/node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! cwd /config/node-red/node_modules/lzma-native
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! node -v v16.15.0
2022-07-19T18:06:54.849Z [err] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
2022-07-19T18:06:54.849Z [err] npm 
2022-07-19T18:06:54.850Z [err] ERR! node-pre-gyp ERR! not ok
2022-07-19T18:06:54.861Z [err] 
2022-07-19T18:06:54.861Z [err] npm ERR! A complete log of this run can be found in:
2022-07-19T18:06:54.861Z [err] npm ERR!     /root/.npm/_logs/2022-07-19T18_06_36_534Z-debug-0.log
2022-07-19T18:06:54.891Z rc=1`

**Comment by Wilano** [comment]
Same Issue:


npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> lzma-native@4.0.6 install /root/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.6 and node@14.20.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp: Call to 'sh liblzma-config.sh "/root/node_modules/lzma-native/build" "/root/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.35-3-pve
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /root/node_modules/lzma-native
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Linux 5.15.35-3-pve
node-pre-gyp ERR! command "/usr/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/node_modules/lzma-native
node-pre-gyp ERR! node -v v14.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/node_modules/lzma-native/binding-v4.0.6-node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-07T09_12_31_152Z-debug.log



**Snippets out of the logfile:**

4505 silly install node-pre-gyp@0.11.0
4506 info lifecycle node-pre-gyp@0.11.0~install: node-pre-gyp@0.11.0
4507 silly install lzma-native@4.0.6
4508 info lifecycle lzma-native@4.0.6~install: lzma-native@4.0.6
4509 verbose lifecycle lzma-native@4.0.6~install: unsafe-perm in lifecycle false
4510 verbose lifecycle lzma-native@4.0.6~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/node_modules/lzma-native/node_modules/.bin:/root/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u>
4511 verbose lifecycle lzma-native@4.0.6~install: CWD: /root/node_modules/lzma-native
4512 silly lifecycle lzma-native@4.0.6~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build && rimraf build' ]
4513 silly lifecycle lzma-native@4.0.6~install: Returned: code: 1  signal: null
4514 info lifecycle lzma-native@4.0.6~install: Failed to exec install script
4515 timing action:install Completed in 1307ms
4516 verbose unlock done using /root/.npm/_locks/staging-4b9e621e77c1ced6.lock for /root/node_modules/.staging
4517 timing stage:rollbackFailedOptional Completed in 123ms
4518 timing stage:runTopLevelLifecycles Completed in 7457ms
4519 silly saveTree root

........

4520 warn enoent ENOENT: no such file or directory, open '/root/package.json'
4521 verbose enoent This is related to npm not being able to find a file.
4522 warn root No description
4523 warn root No repository field.
4524 warn root No README data
4525 warn root No license field.
4526 verbose stack Error: lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
4526 verbose stack Exit status 1
4526 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
4526 verbose stack     at EventEmitter.emit (events.js:400:28)
4526 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4526 verbose stack     at ChildProcess.emit (events.js:400:28)
4526 verbose stack     at maybeClose (internal/child_process.js:1088:16)
4526 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
4527 verbose pkgid lzma-native@4.0.6
4528 verbose cwd /root
4529 verbose Linux 5.15.35-3-pve
4530 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "node-red-contrib-speedtest"
4531 verbose node v14.20.1
4532 verbose npm  v6.14.17
4533 error code ELIFECYCLE
4534 error errno 1
4535 error lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
4535 error Exit status 1
4536 error Failed at the lzma-native@4.0.6 install script.
4536 error This is probably not a problem with npm. There is likely additional logging output above.
4537 verbose exit [ 1, true ]

**Comment by joaopedros2** [comment]
same here:

```
-----------------------------------------------------------
2025-07-10T10:13:31.056Z Install : node-red-contrib-speedtest 1.1.0

2025-07-10T10:13:27.727Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-speedtest@1.1.0
2025-07-10T10:13:27.899Z [err] npm warn Unknown builtin config "globalignorefile". This will stop working in the next major version of npm.
2025-07-10T10:13:27.900Z [err] npm warn Unknown builtin config "python". This will stop working in the next major version of npm.
2025-07-10T10:13:27.900Z [err] npm warn Unknown env config "globalignorefile". This will stop working in the next major version of npm.
2025-07-10T10:13:27.900Z [err] npm warn Unknown env config "python". This will stop working in the next major version of npm.
2025-07-10T10:13:32.893Z [err] npm warn deprecated osenv@0.1.5: This package is no longer supported.
2025-07-10T10:13:32.975Z [err] npm warn deprecated are-we-there-yet@1.1.7: This package is no longer supported.
2025-07-10T10:13:32.996Z [err] npm warn deprecated npmlog@4.1.2: This package is no longer supported.
2025-07-10T10:13:33.100Z [err] npm warn deprecated gauge@2.7.4: This package is no longer supported.
2025-07-10T10:13:33.100Z [err] npm warn deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
2025-07-10T10:13:33.976Z [err] npm error code 1
2025-07-10T10:13:33.976Z [err] npm error path /config/node_modules/lzma-native
2025-07-10T10:13:33.976Z [err] npm error command failed
2025-07-10T10:13:33.976Z [err] npm error command sh -c node-pre-gyp install --fallback-to-build && rimraf build
2025-07-10T10:13:33.976Z [err] npm error Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64 --napi_version=10 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127 --python=/usr/bin/python3' (1)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp info it worked if it ends with ok
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp info using node-pre-gyp@0.11.0
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp info using node@22.16.0 | linux | x64
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp WARN Using request for node-pre-gyp https download 
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp info check checked for "/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64/lzma_native.node" (not found)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v127-linux-x64.tar.gz
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v127-linux-x64.tar.gz
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v127-linux-x64.tar.gz 
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.6 and node@22.16.0 (node-v127 ABI, musl) (falling back to source compile with node-gyp) 
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.6-node-v127-linux-x64.tar.gz 
2025-07-10T10:13:33.976Z [err] npm error gyp info it worked if it ends with ok
2025-07-10T10:13:33.976Z [err] npm error gyp info using node-gyp@11.2.0
2025-07-10T10:13:33.976Z [err] npm error gyp info using node@22.16.0 | linux | x64
2025-07-10T10:13:33.976Z [err] npm error gyp info ok 
2025-07-10T10:13:33.976Z [err] npm error gyp info it worked if it ends with ok
2025-07-10T10:13:33.976Z [err] npm error gyp info using node-gyp@11.2.0
2025-07-10T10:13:33.976Z [err] npm error gyp info using node@22.16.0 | linux | x64
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python 
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - executable path is ""
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - "" could not be run
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python Python is not set from environment variable PYTHON
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python checking if "python3" can be used
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - executable path is ""
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - "" could not be run
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python checking if "python" can be used
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - executable path is ""
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - "" could not be run
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python 
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python **********************************************************
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python You need to install the latest version of Python.
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python you can try one of the following options:
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python (accepted by both node-gyp and npm)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - Set the environment variable PYTHON
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python - Set the npm configuration variable python:
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python For more information consult the documentation at:
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python **********************************************************
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! find Python 
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! configure error 
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack Error: Could not find any Python installation to use
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack at PythonFinder.findPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack at async configure (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! stack at async run (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! System Linux 6.12.23-haos
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64" "--napi_version=10" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127" "--python=/usr/bin/python3"
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! cwd /config/node_modules/lzma-native
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! node -v v22.16.0
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! node-gyp -v v11.2.0
2025-07-10T10:13:33.976Z [err] npm error gyp ERR! not ok 
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! build error 
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/config/node_modules/lzma-native/binding-v4.0.6-node-v127-linux-x64 --napi_version=10 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127 --python=/usr/bin/python3' (1)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! System Linux 6.12.23-haos
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! command "/usr/bin/node" "/config/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! cwd /config/node_modules/lzma-native
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! node -v v22.16.0
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
2025-07-10T10:13:33.976Z [err] npm error node-pre-gyp ERR! not ok
2025-07-10T10:13:33.978Z [err] npm error A complete log of this run can be found in: /root/.npm/_logs/2025-07-10T10_13_27_833Z-debug-0.log
2025-07-10T10:13:33.993Z rc=1
```
